apiVersion: v1
kind: Service
metadata:
  name: booking-master-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: booking-master
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000 
