apiVersion: v1
kind: PersistentVolume
metadata: 
  name: rabbitmq-pv
spec: 
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/rabbitmq"
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname 
          operator: In
          values:
          - worker-192.168.0.5
