apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret 
type: Opaque

stringData:
  POSTGRES_USER: "fixmaster_user"
  POSTGRES_PASSWORD: "SuperSecretPass123"
  POSTGRES_DB: "fixmaster_db"
  POSTGRES_POSTGRES_PASSWORD: "RootSecretPass123"